### ISSUE TITLE
Font family with spaces are not wrapped by quotes

### ISSUE THREAD

**Issue by Cronos87** [Dan503/font-face-generator#14]
I'm using the following example:

```scss
@include font-face((
  'Open Sans' : (
    300 : 'open-sans-light'
  )
));
```

and got this result:

```css
@font-face {
  font-family: Open Sans;
  font-style: normal;
  font-weight: 300;
  src: local("☺"), url(../fonts/Open-Sans/open-sans-light.woff) format("woff");
}
```

As you can see, the `font-family` is not wrapped with quotes.

Am I doing something wrong? I'm using the documentation example by the way.

**EDIT:**

Everything is fine, it was related to my CSS optimiser 😅
